name: CD
on:
  push:
    branches:
      - master
jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:  
      - name: Check out repository
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Deploy to github pages
        run: npm run deploy
