name: CD
on:
  push:
    branches:
      - master
jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:  
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Deploy to github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
